### ISSUE TITLE
a: windows gives me a black window.

### ISSUE THREAD

**Issue by dertuxmalwieder** [as/a#140]
C:\> go get github.com/as/a
    C:\> a
    guide
    CreateFile guide: Das System kann die angegebene Datei nicht finden.
    .
    +Errors
    CreateFile +Errors: Das System kann die angegebene Datei nicht finden.

I get a black, empty window. That's all.

**Comment by dertuxmalwieder** [comment]
A different Windows 10 machine has no such issue, by the way.

**Comment by dertuxmalwieder** [comment]
From CPU-Z:

	Specification		Intel(R) Core(TM) i5 CPU         650  @ 3.20GHz
	CPUID			6.5.2
	Microcode Revision	0xE

**Comment by dertuxmalwieder** [comment]
FYI, the problem persists with the newest updates.

**Comment by as** [comment]
This issue is next on the hit list

**Comment by dertuxmalwieder** [comment]
The problem seems to be gone with 0.7.8. Thank you! :-)
