### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by nunojesus** [as/a#142]
Hi Hello I am looking for open source projects to contribute with graphical design, I have been contributing to several opensource projects for free, I would like to know if you are interested that I make a logo for this your project ?.
It´s all free, I just need to know what do you want for the logo.

Greetings

Nuno Jesus

**Comment by as** [comment]
I sincerely appreciate the offer, but this project doesn't need a logo right now.

**Comment by nunojesus** [comment]
Ok, then.

Greetings
