### ISSUE TITLE
Constant overflows int

### ISSUE THREAD

**Issue by asampal** [as/a#42]
Not sure this is an issue, but I get the following:

```
> go get -u -t github.com/as/a
# github.com/as/edit
c:\devenv\projects\_go\src\github.com\as\edit\lex.go:33:21: constant 9223372036854775807 overflows int
```

**Comment by asampal** [comment]
Hmm, I switched to 32 bit Go to try something out a little while ago and had forgotten to switch back. Thanks for reminding me.

**Comment by as** [comment]
No problem, thanks for reporting the issue. I doubt I would have found this one.
