### ISSUE TITLE
a: edit: Crashes on '^' or '$'

### ISSUE THREAD

**Issue by jubei85** [as/a#78]
Win7/64
go 1.9
crashed if input commands: 1,$s, 1,$p and etc...

**Comment by as** [comment]
There are two separate issues here:
- The lack of the print command 'p'
- The crash that occurs upon a `^` or `$` symbol

Because the latter causes the crash, we will address that issue here. A separate issue will be created for missing `p`.

**Comment by as** [comment]
Those specific constructions should work for the most part. Added p and s, but the edit program is overdue for refactoring. 

```
Some tests
Edit ,x,func.+,=
Edit 2,$p
Edit ^,10,p
```
